apiVersion: v1
kind: Service
metadata:
  labels:
    app: training
  name: trainingsvc
spec:
  ports:
  - nodePort: 30001
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: training
  type: NodePort
